# Generated by Django 3.2.4 on 2021-06-13 04:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='name',
            field=models.CharField(help_text='Enter a category (e.g. School)', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Thing must be greater than 1 character')]),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Task must be greater than 1 character')])),
                ('description', models.CharField(max_length=300)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.thing')),
            ],
        ),
    ]
